### PR TITLE
Feat/hide menu buttons

### LINKED ISSUE #15: Hide or grey out "Assign to other" button
This should align with what we choose when we either hide or grey out on issue #14 I think?

### PR DESCRIPTION
**Pull request by teesloane**
closes #15
I mucked up this PR becuase I forgot to make a new branch (and accidentally just pushed to my last merged branch (`styling/message-component`)... so I made a new branch and pulled everything in. so if the history looks weird that is why.

## Screenshot

screenshot 2017-03-15 11 20 00

### CODE REVIEW

**Comment by mihok** [comment]
So I dont think we want to hide the message bar at the top all together. There is one button in the Wireframe to "Mark as done" that should stay up there

**Comment by teesloane** [comment]
kk will update will keep the bar but not the buttons (i don't think they should be greyed out as it could confuse the user.

**Comment by teesloane** [comment]
## update screenshot:
screenshot 2017-03-15 11 45 33

**Comment by mihok** [comment]
LGTM

**Pull request merged**
